version: "3"
services:
  test-django:
    build: .
    container_name: test-back
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static/
      - media_volume:/app/media/
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: test-postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  postgres_data:
